In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("online_retail_II.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'online_retail_II.xlsx'

In [ ]:
df = pd.read_excel("../DataSet/online_retail_II.xlsx")

In [7]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107927
Country             0
dtype: int64

In [10]:
df = df.dropna(subset=["Customer ID"])

In [11]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [14]:
df = df[-df["Invoice"].astype(str).str.startswith("C")]

In [15]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [16]:
df["Quantity"] = df["Quantity"].astype(int)

C:\Users\Admin\AppData\Local\Temp\ipykernel_6376\3261162328.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quantity"] = df["Quantity"].astype(int)

In [17]:
df[["Quantity"].dtype

SyntaxError: incomplete input (3906368463.py, line 1)

In [18]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce").astype("Int64")

C:\Users\Admin\AppData\Local\Temp\ipykernel_6376\2830958091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce").astype("Int64")

In [19]:
df = df.copy()

In [20]:
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce").astype("Int64")

In [21]:
df["Quantity"].dtype

Int64Dtype()

In [22]:
df["Price"] = pd.to_numeric(df["Price"], errors="coerce").round(2)

In [23]:
df["Price"].dtype

dtype('float64')

In [24]:
df = df[(df["Quantity"] > 0) & (df["Price"] > 0)].copy()

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 407650 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      407650 non-null  object
 1   StockCode    407650 non-null  object
 2   Description  407650 non-null  object
 3   Quantity     407650 non-null  Int64
 4   InvoiceDate  407650 non-null  datetime64[ns]
 5   Price        407650 non-null  float64
 6   Customer ID  407650 non-null  float64
 7   Country      407650 non-null  object
dtypes: Int64(1), datetime64[ns](1), float64(2), object(4)
memory usage: 28.4+ MB

In [26]:
df.to_csv("cleaned_retail.csv", index=False)

In [27]:
!pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyarrow in c:\programdata\anaconda3\lib\site-packages (16.1.0)
Requirement already satisfied: numpy>=1.16.6 in c:\programdata\anaconda3\lib\site-packages (from pyarrow) (1.26.4)

In [28]:
df.to_parquet("cleaned_retail.parquet", index=False)

ArrowInvalid: ("Could not convert '79323P' with type str: tried to convert to int64", 'Conversion failed for column StockCode with type object')

In [29]:
df["StockCode"] = df["StockCode"].astype(str)

In [30]:
df["Customer ID"] = df["Customer ID"].astype(str)

In [31]:
df.to_parquet("cleaned_retail.parquet", index=False)

In [32]:
df = df.copy()

df["StockCode"] = df["StockCode"].astype(str)
df["Customer ID"] = df["Customer ID"].astype(str)

In [33]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [34]:
df.shape

(407650, 8)

In [35]:
df.describe()

        Quantity                    InvoiceDate          Price
count   407650.0                         407650  407650.000000
mean   13.586017  2010-07-01 10:18:51.269422336       3.294551
min          1.0            2009-12-01 07:45:00       0.030000
25%          2.0            2010-03-26 14:01:00       1.250000
50%          5.0            2010-07-09 15:48:00       1.950000
75%         12.0            2010-10-14 17:09:00       3.750000
max      19152.0            2010-12-09 20:01:00   10953.500000
std    96.842382                            NaN      34.758556